export const USER_REGISTER_REQUEST = 'USER REGISTER REQUEST';
export const USER_REGISTER_SUCCESS = 'USER REGISTER SUCCESS';
export const USER_REGISTER_FAILURE = 'USER REGISTER FAILURE';

export const USER_SIGNIN_REQUEST = 'USER SIGNIN REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER SIGNIN SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER SIGNIN FAILURE';
